# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='date_post',
            field=models.CharField(default='2018/06/28', max_length=1000),
        ),
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.CharField(max_length=1000),
        ),
    ]
